[tool.poetry]
name = "neuro-trainer"
version = "0.1.0"
description = ""
authors = ["omigutin <migutin83@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
matplotlib = {version = "^3.9", optional = true}
PySide6 = {version = "^6.9.1", optional = true, markers = "python_version < '3.14'"}
pyyaml = "^6.0.2"
ultralytics = "^8.3.179"

[tool.poetry.extras]
gui = ["PySide6", "matplotlib"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
